### ISSUE TITLE
AgileCRM action titles are blank when configuring workflows

### ISSUE THREAD

**Issue by fhaps** [Prospress/automatewoo-agilecrm#3]
### Summary of issue:

When trying to create a new workflow that works with AgileCRM, the list of actions appears blank. The spacing for them is there, but the titles are gone.

### Steps needed to reproduce:

1. Install AutomateWoo
2. Install AutomateWoo AgileCRM Add-on
3. Configure the AgileCRM credentials under AutomateWoo > Settings > AgileCRM.
4. Add a new workflows.
5. Add a new action. In the dropdown menu scroll down to the "Other" section.

### Screencast showcasing the issue:

![Screen Capture on 2021-01-11 at 17-31-56](https://user-images.githubusercontent.com/4167300/104252106-1a8b3f80-54d6-11eb-8d84-2cb76d792542.gif)

![](https://d.pr/i/4shzg0+)
Image Link: https://d.pr/i/4shzg0

3640462-zen

**Comment by fhaps** [comment]
I set this one to `CRITICAL` since it renders the AgileCRM useless.

**Comment by haszari** [comment]
Does the site have the AgileCRM plugin installed? Looking at our docs this may be a requirement.

- https://www.agilecrm.com/woocommerce-crm
- https://automatewoo.com/addons/agilecrm/

~~I had a quick attempt at reproducing the issue, but I couldn't get an API key for AgileCRM. I signed up on the free plan, so possibly the REST API is not supported in the free plan?~~

Update: found the REST API key, installed & activated AgileCRM plugin and I can reproduce the issue:

<img width="669" alt="Screen Shot 2021-01-12 at 1 25 32 PM" src="https://user-images.githubusercontent.com/4167300/104253604-c5e9c380-54d9-11eb-943a-462952970e49.png">

**Comment by fhaps** [comment]
> Does the site have the AgileCRM plugin installed? Looking at our docs this may be a requirement.

I also thought this might be the case but I tested by installing the Agile CRM WooCommerce plugin and it didn't make a difference.

**Comment by danbitzer** [comment]
I've opened a [PR to fix this issue](https://github.com/woocommerce/automatewoo-agilecrm/pull/4).

**Comment by danbitzer** [comment]
@fhaps this issue is now fixed in 1.4.6. Thanks for reporting!
