### ISSUE TITLE
Enhancement: Improve formatting of text for {{ order.items }} in `Add Note to Contact` action

### ISSUE THREAD

**Issue by kaushikasomaiya** [Prospress/automatewoo-agilecrm#6]
When we use {{ order.items }} variable in `Add Note to Contact` action - it produces a lot of line breaks similar to this issue: https://github.com/woocommerce/automatewoo/issues/1144

Is it possible to create a separate variable that is specific to this add-on and creates a list of products in the following (simplified) way:

- Black Shoes x 3 ($10)
- White Hat x 2 ($45)

Or if we could reduce the number of line breaks.

![image](https://d.pr/i/Rlznia+)

**Comment by findingsimple** [comment]
> Is it possible to create a separate variable 

It's possible but I don't think we'll ever prioritize it over other AW work.

I'd recommend Merchants investigate creating a custom variable for themselves https://automatewoo.com/docs/variables/custom-variables/
